### ISSUE TITLE
silent failure to vote or pose question on insufficient funds

### ISSUE THREAD

**Issue by dckc** [Agoric/dapp-econ-gov#10]
EC members struggled to vote today. Signing with keplr + ledger seemed to go ok, but then their proposal would fail to appear or a question would fail for lack of quorum.

With seconds to spare, we diagnosed the problem as insufficient funds using the browser console:

```
sign spend action { ... }
SES_UNHANDLED_REJECTION: (Error#3)
Error#3: Broadcasting transaction failed with code 20 (codespace: sdk). Log: controller refused message admission: 150000uist is smaller than 200000uist: insufficient funds: mempool is full
  at new BroadcastTxError
  at Dt.broadcastTx
  at async Object.submitSpendAction
```

That is: the 0.20IST batch fee threshold came up, but the voter had only 0.15IST in their account. When supplied with funds, the vote went thru and the **board02152** proposal passed. (whew!)

Diagnosing this was complicated by
 - #7 

and by the fact that walletStatus data can be pruned:
 - https://github.com/Agoric/agoric-sdk/issues/6184

## Expected behavior

**insufficient funds** error should be prominently displayed.

cc @rowgraus @Chris-Hibbert @warner @turadg @samsiegart

**Comment by turadg** [comment]
> insufficient funds error should be prominently displayed.

This ticket is on econ-gov, but the problem seems more general. Should such an error be displayed in Wallet UI?

**Comment by dckc** [comment]
The rejection seems to get dropped at...

https://github.com/Agoric/dapp-econ-gov/blob/3dfe87b10291d43c1b7eb5a8e3edb08c7c818eff/src/components/ProposeParamChange.tsx#L79

I don't believe the wallet UI is involved (though I suppose it could have a similar bug)

**Comment by dckc** [comment]
The wallet UI seems to handle this error as expected:

https://github.com/Agoric/wallet-app/blob/84664b73b4f889e30d455a5a90b0c92aa270ddc6/src/components/Offer.jsx#L75-L76
