### ISSUE TITLE
Update Econ-Gov UI to handle + validate new git hash input format

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-econ-gov#109]
The Econ Gov UI can take any string that the EC pastes into the field (which is subsequently voted in by EC as the endorsed UI - to become the latest UI version on chain).

We should add client-side validation so it helps guide them with the expected value, ensuring it's in the form of a valid git url, or ipfs hash for backward compatibility

**Comment by otoole-brendan** [comment]
Updated to reflect no contract update required. Change is only client-side for validation

**Comment by LuqiPan** [comment]
Is this absolutely necessary or a nice to have? Can we solve this with some other way, i.e. documentations, educations, etc?

**Comment by samsiegart** [comment]
It's not necessary, it's a nice-to-have. Yes, documentation/personal guidance for the EC would be warranted either way.
