### ISSUE TITLE
Update Econ-gov UI to be more user-friendly for the non-technical EC users

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-econ-gov#12]
## What is the Problem Being Solved?
As it stands, the Econ-Gov UI tool is not simple and intuitive to the intended non-technical user i.e Econ Committee members. See list of superficial text, spacing and format changes for relevant features, input fields, buttons etc.

## Description of the Design

1) ‘Vote’ tab:

- [ ] Give user feedback that a vote successfully went through (High Priority) (Being worked on via https://app.zenhub.com/workspaces/agoric-primary-workspace-5fda3aa55dbe1100117cbaae/issues/agoric/dapp-econ-gov/7 )
- [x] Simplify 'Yes' and 'No' buttons by removing accompanying technical jargon/code (remove handle, type, quorum and method). Include only relevant information i.e. for mint limit on USDC_axl it should include mint limit amount and USDC_axl as the anchor token the proposal is seeking to change. Currently the user does not know who what token the mint limit change is being proposed. (High Priority)
- [ ] ~Ability to vote on multiple queued proposals (High Priority)~ EDIT: https://github.com/Agoric/dapp-econ-gov/issues/14

2) For ‘Propose Change’ tab:

- [x] Clearly mark fees as percentages (High Priority) (Work being tracked via https://app.zenhub.com/workspaces/agoric-primary-workspace-5fda3aa55dbe1100117cbaae/issues/agoric/agoric-sdk/6460)
- [x] Change 'Anchor' to 'Contract' (High Priority)
- [x] Fix strange input behavior round zeros
- [x] The below UI text changes:
‘GiveMintedFee’ -> ‘Set GiveMinted Fee (Fee charged when user swaps IST for supported stable token)’ (High Priority)
‘WantMintedFee’ -> ‘Set WantMinted Fee (Fee charged when user swaps supported stable token for IST)’ (High Priority)
‘wantMinted’ -> ‘Propose IST minting pause (Users will not be able to swap supported stable tokens for IST in PSM) (wantMinted)’ (High Priority)
‘giveMinted’ ->  ‘Propose IST burning pause (Users will not be able to swap IST for supported stable tokens in PSM) (giveMinted)’ (High Priority)
‘Propose param change’ -> ‘Propose Parameter Change Proposal’ (High Priority)
‘Propose set to pause’ -> ‘Propose Pause Offer Proposal’ (High Priority)
‘VoteOnParamChange’ -> ‘Propose Vote to Change Parameters’
‘VoteOnPauseOffers’ -> ‘Propose Vote to Pause Offers’
‘MintLimit’ -> ‘Mint Limit’

3)On History tab

- [ ] Pending Proposal shows current status of the vote (Status options: 1) Passing, 2) Failing, 3) Quorum not met) (High Priority)
- [ ] Pending Proposal shows votes for/against by address

## Security Considerations

mitigate EC user error like incorrect proposals because of poor usability

## Test Plan
1) make changes
2) PM reviews and approves
3) changes deployed

**Comment by dckc** [comment]
> Simplify 'Yes' and 'No' buttons by removing accompanying technical jargon/code (remove handle, type, quorum and method)

Are you _sure_ you want to remove **handle**? That's the one thing that uniquely identifies a question. I trust the EC keeps meeting records... maybe their own spreadsheet of proposed changes. I recommend they include question handles in those records.

**Comment by otoole-brendan** [comment]
Closing this issue in favor of cleaned up https://github.com/Agoric/dapp-econ-gov/issues/26
