### ISSUE TITLE
Econ Gov can execute manual burn of IST to reduce debt shortfall (Reserve)

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-econ-gov#33]
**Is your feature request related to a problem? Please describe.**

The EC needs to be able to specify how much IST to burn from the reserve manually to reduce debt shortfall

**Describe the solution you'd like**

EC should be able to enter an amount in a field and hit 'execute IST burn'

**Describe alternatives you've considered**

**Additional context**

This would be the first governance API call. May require contract changes.

**Comment by otoole-brendan** [comment]
@turadg please estimate

**Comment by dckc** [comment]
## Show current shortfall etc.?

Should we show some of these metrics to the EC when they're choosing how much to burn?

```
$ agoric follow -B https://ollinet.agoric.net/network-config :published.reserve.metrics
{
  allocations: {},
  shortfallBalance: {
    brand: slot(0,"Alleged: IST brand"),
    value: 0n,
  },
  totalFeeBurned: {
    brand: slot(0),
    value: 0n,
  },
  totalFeeMinted: {
    brand: slot(0),
    value: 0n,
  },
}
```
