### ISSUE TITLE
Devnet Econ Gov UI not responsive and 'invalid time value' error upon clicking created vault 

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-econ-gov#52]
**Describe the bug**
Note: this scope of this ticket has been expanded to cover other Devnet-related issues noticed in Vaults UI (see supplementary comments below)

Attempting to test adding a new oracle node operator in coordination with Simply Staking (Adding a 6th oracle node operator) but can't sign Keplr transaction after I propose on Econ Gov UI on devnet.

**To Reproduce**

1. Go to https://f4964f27.dapp-econ-gov.pages.dev/ or https://econ-gov.inter.trade/ 
2. Click on 'Vaults'
3. Select 'Add Oracle Operator'
4. Select 'ATOM-USD' feed
5. Paste test address to add: agoric1cuwd8uhemfx26fmzvrdy295ltscyl350mz5kek
6. Click 'Add'
7. Hit 'Propose'

**Expected behavior**
I should be able to sign Keplr txn to submit to chain

**Screenshots**
 ![image.png](https://images.zenhubusercontent.com/634474599b165f9f64feb7ec/1411683c-6c88-4d30-8792-750440387619)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by otoole-brendan** [comment]
Got as far as proposing a change but then couldn't vote. 
Can't select manager from drop down here also 
![image](https://github.com/Agoric/dapp-econ-gov/assets/93355546/561a1d1c-35ad-4143-9787-fb8372f332a2)

**Comment by otoole-brendan** [comment]
unable to propose change (tells me invitation charter accepted): 
![image](https://github.com/Agoric/dapp-econ-gov/assets/93355546/4d410aef-1420-4681-b40d-e892e66c599d)

**Comment by otoole-brendan** [comment]
Managed to create a vault using [(URL)](https://bafybeica44rd5i6okwsdnjawhpyb3n3yc6jj2xwfc4hwqtfqq6lgzlimxy.ipfs.cf-ipfs.com/?wallet=main#/vaults) but when I click on vault I get:
![image](https://github.com/Agoric/dapp-econ-gov/assets/93355546/bde19d6a-da04-445f-b6e2-30faa1f352c6)

**Comment by otoole-brendan** [comment]
Console log: 
![image](https://github.com/Agoric/dapp-econ-gov/assets/93355546/b16eb26f-8fa8-462a-b877-0f9b462d2108)

**Comment by ivanlei** [comment]
Assigning to @otoole-brendan to verify things now work on devnet

**Comment by otoole-brendan** [comment]
Can confirm Devnet is healthy again since RC roll...comfortable that the above is no longer a problem
