### ISSUE TITLE
Change 'EndorsedUI' to 'ReferencedUI' in Econ Gov UI

### ISSUE THREAD

**Issue by otoole-brendan** [Agoric/dapp-econ-gov#54]
**Is your feature request related to a problem? Please describe.**

Change 'EndorsedUI' text in Econ Gov UI to 'ReferencedUI'.

This accompanies #125

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

See #125.

**Comment by otoole-brendan** [comment]
@samsiegart can you confirm if this would also need a contract change somewhere since it pertains to a governed param?

**Comment by samsiegart** [comment]
@otoole-brendan Yes. The governed param is called 'EndorsedUI'.
