### ISSUE TITLE
Add Polkachu's RPC endpoint

### ISSUE THREAD

**Issue by sufyaankhan** [Agoric/dapp-econ-gov#79]
**Is your feature request related to a problem? Please describe.**
Yes, recently we found that a community RPC KJnodes node was down. Developers and users are in need of a more reliable, faster, and secure method to interact with the Agoric blockchain.

**Describe the solution you'd like**
We propose the integration of Polkachu's dedicated RPC endpoint to the Agoric platform. 

"rpc": "[https://agoric-agor-rpc.polkachu.com:443](https://agoric-agor-rpc.polkachu.com/)", 
"api": "https://agoric-agor-api.polkachu.com/", 
"grpc": "agoric-agor-grpc.polkachu.com:14490"

This solution encompasses:

Endpoint Integration: We update the Agoric platform to route traffic to Polkachu's services.
Load Balancing: Utilizing load balancers to effectively distribute traffic between Polkachu's endpoint and the current infrastructure.
Monitoring Systems: Establishing comprehensive monitoring and logging to observe the health and performance of the endpoint. https://uptime.betterstack.com/team/38938/monitors/1521088

**Comment by ivanlei** [comment]
Updated to

```
{
  "chainName": "agoric-3",
  "gci": "edef208d407403e6f478bc33dcf7bb294febc5bc6a423c720f0c9c50da5176d5",
  "peers": [
    "a26158a5cbb1df581dd6843ac427191af76d6d5d@104.154.240.50:26656",
    "6e26a1b4afa6889f841d7957e8c2b5d50d32d485@95.216.53.26:26656"
  ],
  "rpcAddrs": [
    "https://agoric.rpc.kjnodes.com:443",
    "https://agoric-agor-rpc.polkachu.com:443"
  ],
  "apiAddrs": [
    "https://agoric.api.kjnodes.com:443",
    "https://agoric-agor-api.polkachu.com:443"
  ],
  "oldRpcAddrs": [
    "https://agoric-rpc.polkachu.com:443",
    "https://main.rpc.agoric.net:443",
    "https://api.agoric.nodestake.top:443"
  ],
  "oldApiAddrs": [
    "https://agoric-api.polkachu.com:443",
    "https://main.api.agoric.net:443",
    "https://api.agoric.nodestake.top:443"
  ],
  "dappInterJumperBanner": "",
  "seeds": [],
  "notices": []
}
```
